### PR TITLE
Restyle all keyboard shortcuts inside posts

### PR DESCRIPTION
**Pull request by Bartuz**
We found in https://github.com/railsgirls/railsgirls.github.com/pull/255#issuecomment-141504437 that we can improve a bit keyboard shortcuts inside posts.

To make content consistent in style I introduced guideline for shortcuts in [README](https://github.com/railsgirls/railsgirls.github.com/pull/256/files#diff-04c6e90faac2675aa89e2176d2eec7d8R40)

### CODE REVIEW

**Comment by Bartuz** [comment]
It looks like this now
screen shot 2015-09-18 at 19 02 10

**Comment by Bartuz** [comment]
@chastell https://github.com/railsgirls/railsgirls.github.com/pull/256

**Comment by chastell** [comment]
Oh wow, this is most awesome. Thanks so much! :sparkles:

**Comment by vesan** [comment]
This is sweet! Thanks @Bartuz.

**Pull request merged**
