### PR TITLE
Farwell ninefold. :cry:

### LINKED ISSUE #234: Remove Ninefold content from site (sunsetting Rails deployment)
Adding this here, if someone has time to update before me :) 

--

Hi Rails Girls Team,
Thank you for your support of the Ninefold Rails platform over the last year and a half.
You may have recently heard Ninefold is sun-setting the Rails App Deployment feature to focus more on IaaS and Docker.
As such, I kindly request you remove Ninefold related Rails content from the Rails Girls website, as the content will no longer be applicable to your visitors.
The references to Ninefold on your website can be found here:
·         http://guides.railsgirls.com
·         http://guides.railsgirls.com/app/
·         http://guides.railsgirls.com/touristic-autism_intro/
·         http://guides.railsgirls.com/ninefold/
If you have any questions, please let me know.
Many thanks!
Dennis
Digital Marketing Manager
ninefold.com
twitter: @dennisgraham7
skype: dennis.graham7

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Fixes #234.

### CODE REVIEW

**Comment by vesan** [comment]
Cheers @JuanitoFatas!

**Comment by hsbt** [comment]
:+1:

**Comment by JuanitoFatas** [comment]
Thanks! @vesan and @hsbt  My pleasure!

**Comment by lindaliukas** [comment]
Thank you @JuanitoFatas <3 You're the best.

**Pull request merged**
