### PR TITLE
Add Authentication (user accounts) with Devise

### PR DESCRIPTION
**Pull request by blossomica**
Hello I noticed that the URL here does not work due to the trailing slash. I tried to fix it by omitting it. 
Please check it and let me know if you need any alternation or me to merge both commits into one. 
Thank you.

### CODE REVIEW

**Comment by vesan** [comment]
@blossomica It seems to work: http://guides.railsgirls.com/devise Where did you see it not working?

**Comment by blossomica** [comment]
@vesan - Here: http://guides.railsgirls.com/app when you go to the end and click Guide number 5, the url there is broken. The guide exists and works as you said but the URL seems to not be pointing to it correctly due to the trailing slash.

**Comment by vesan** [comment]
Oh, you are right. I misread the diff.

Thanks for fixing it!

**Comment by blossomica** [comment]
@vesan - You are welcome :) It is my pleasure!

**Pull request merged**
